---
- name: Run common provision tasks as provision user
  vars:
    ansible_user: "{{ provision_user_username }}"
    ansible_become_pass: "{{ provision_user_password }}"
  block:
    - name: Install latest apt packages
      ansible.builtin.apt:
        update_cache: yes
        upgrade: full
      when: provision_full_upgrade | bool
