---
- name: Set provision username fact to ansible
  ansible.builtin.set_fact:
    provision_user_username: ansible
  when: provision_user_username is not defined

- name: Prompt user for provision username
  ansible.builtin.pause:
    prompt: Enter username for provision user
    echo: yes
  when: provision_user_username == ""
  register: _provision_username_input

- name: Set provision username fact
  ansible.builtin.set_fact:
    provision_user_username: "{{ _provision_username_input.user_input }}"
  when: provision_user_username == ""

- name: Prompt user for provision password
  ansible.builtin.pause:
    prompt: Enter password for provision user
    echo: no
  when: provision_user_password is not defined or provision_user_password == ""
  register: _provision_password_input

- name: Set provision password fact
  ansible.builtin.set_fact:
    provision_user_password: "{{ _provision_password_input.user_input }}"
  when: provision_user_password is not defined or provision_user_password == ""

- name: Export provision user facts
  ansible.builtin.set_fact:
    provision_user_username: "{{ provision_user_username }}"
    provision_user_password: "{{ provision_user_password }}"
    provision_user_keep: "{{ provision_user_keep }}"
